 on:
  push:
    branches:
    - main

 jobs:
   e2etest:
    runs-on: windows-latest # or macos-latest, ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: microsoft/playwright-github-action@v1
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install
      - name: run e2e-tests
        run: npm run e2etest -- --tags @login_happy